// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link from "next/link";
import * as BlockContentToReact from "@sanity/block-content-to-react";

function BioView(Props) {
  var content = Props.content;
  return React.createElement("div", {
              className: "flex flex-col p-8 space-y-4 bg-white border border-gray-100 rounded-md shadow-lg"
            }, React.createElement("h1", {
                  className: "text-4xl font-bold leading-none tracking-wider text-gray-900"
                }, "Bio"), React.createElement(BlockContentToReact.default, {
                  blocks: content,
                  renderContainerOnSingleChild: true,
                  className: "prose max-w-none"
                }), React.createElement(Link.default, {
                  href: "/about",
                  children: React.createElement("a", {
                        className: "self-start px-3 py-2 text-lg font-semibold tracking-wider text-white rounded-md shadow-lg focus:outline-none focus:from-teal-500 focus:to-teal-600 hover:from-teal-500 hover:to-teal-600 bg-gradient-to-tr from-teal-400 to-teal-500"
                      }, "Read More")
                }));
}

var BlockContent;

var Link$1;

var make = BioView;

export {
  BlockContent ,
  Link$1 as Link,
  make ,
  
}
/* react Not a pure module */
